<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fsl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{</string>
	<key>foldingStopMarker</key>
	<string>}</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>fslex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.fsharp.begin.fslex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.fsharp.end.fslex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.fsharp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fsharp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(let)\s+([a-z][a-zA-Z0-9'_]*)\s+=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pattern-definition.fslex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.pattern.stupid-goddamn-hack.fslex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?:\s*let)|(?:\s*(rule|$))</string>
			<key>name</key>
			<string>meta.pattern-definition.fsharp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#match-patterns</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(rule|and)\s+([a-z][a-zA-Z0-9_]*)\s+(=)\s+(parse)(?=\s*$)|((?&lt;!\|)(\|)(?!\|))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.fslex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.entrypoint.fslex</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.fslex</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.fslex</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.match-pattern.fslex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:^\s*((and)\b|(?=\|)|$))</string>
			<key>endCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.entry-definition.fslex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pattern-match.fsharp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#match-patterns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.symbol.fslex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.paren-group.fslex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(’|‘|“|”)</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized-character.fslex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[^\']({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.begin.fslex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.action.end.fslex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.action.fslex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.fsharp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>chars</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.char.begin.fslex</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.char.end.fslex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(')([^\\]|\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\]))(')</string>
					<key>name</key>
					<string>constant.character.fslex</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.empty.fsharp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.empty.fsharp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\(\*(?:(\*)| ( )\*)\)</string>
					<key>name</key>
					<string>comment.block.fsharp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\*</string>
					<key>end</key>
					<string>\*\)</string>
					<key>name</key>
					<string>comment.block.fsharp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=[^\\])(")</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>comment.block.string.quoted.double.fsharp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\])</string>
							<key>name</key>
							<string>comment.block.string.constant.character.escape.fsharp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>match-patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.sub-pattern.begin.fslex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.sub-pattern.end.fslex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.pattern.sub-pattern.fslex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#match-patterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-z][a-zA-Z0-9'_]</string>
					<key>name</key>
					<string>entity.name.type.pattern.reference.stupid-goddamn-hack.fslex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bas\b</string>
					<key>name</key>
					<string>keyword.other.pattern.fslex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>eof</string>
					<key>name</key>
					<string>constant.language.eof.fslex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>_</string>
					<key>name</key>
					<string>constant.language.universal-match.fslex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)(\^?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.begin.fslex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.negation.fslex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(])(?!\')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.end.fslex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.pattern.character-class.fslex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>-</string>
							<key>name</key>
							<string>punctuation.separator.character-class.range.fslex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#chars</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\*|\+|\?</string>
					<key>name</key>
					<string>keyword.operator.pattern.modifier.fslex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.pattern.alternation.fslex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#chars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[^\\])(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fsharp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fsharp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.fslex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\$[ \t]*</string>
							<key>name</key>
							<string>punctuation.separator.string.ignore-eol.fsharp</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\])</string>
							<key>name</key>
							<string>constant.character.string.escape.fsharp</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[\|\(\)1-9$^.*+?\[\]]</string>
							<key>name</key>
							<string>constant.character.regexp.escape.fsharp</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?!(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\]|[\|\(\)1-9$^.*+?\[\]]|$[ \t]*))(?:.)</string>
							<key>name</key>
							<string>invalid.illegal.character.string.escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fslex</string>
	<key>uuid</key>	
	<string>84F87013-51E3-4A3D-8473-8EC35A325F81</string>
</dict>
</plist>
